contentType: text_and_ide
editorSettings:
  preCode: ''
  startingCode: "\n"
  postCode: ''
  instructions: "**Aufgabe:**\n\nGebe mit der print-Anweisung das Wort Informatik
    aus.\n"
gradingSettings:
  gradingMethod: ioTestCases
  testCases:
  - outputs:
    - Informatik
    hidden: false
  dueDateGroup:
    enableDueDate: true
    duedate: '2026-02-22T23:00:00.000Z'
pythonRunner: skulpt
pyodideOptions:
  packages: []
